12.oauth
di8905/asky pull request #10
Opened 2016-12-04 12:49 UTC by di8905

2016-12-04 16:36 UTC, vkurennov requested changes

2016-12-04 16:36 UTC, vkurennov commented on app/controllers/omniauth_callbacks_controller.rb
> +    if @user && @user.persisted?
А если условие не выполнится? Будет 500-я ошибка, что не очень хорошо. Надо покрыть тестами этот кейс и что-то вразумительное юзеру написать.

2016-12-04 17:21 UTC, di8905 commented on app/controllers/omniauth_callbacks_controller.rb
> +    if @user && @user.persisted?
Подожди, у меня же сделан на это тест, когда приходят неправильные параметры. Юзеру флеш высвечивается Could not authenticate you from Twitter because "Invalid credentials". В сценарии try to sign in with invalid oauth provider разве это не покрыто?

2016-12-04 17:27 UTC, di8905 commented on app/controllers/omniauth_callbacks_controller.rb
> +    if @user && @user.persisted?
Там devise вполне себе все случаи обрабатывает, и когда токен от провайдера неверный, и когда его совсем нет.

2016-12-05 10:16 UTC, vkurennov commented on app/controllers/omniauth_callbacks_controller.rb
> +    if @user && @user.persisted?
Дело в том, что у тебя похоже не возможен сценарий, когда условие не выполнится. Т.к. в противном случае, у тебя метод common_callback завершится без рендеринга или редиректа, и управление перейдет в экшн контроллера. А т.к. там тоже нет рендеринга или редиректа, то релься попытаются отрендерить вид facebook или twitter, не найдут его и выдадудт 500-ю ошибку. И devise тут вообще никак не поможет, т.к. он не участвует в этом процессе.

Другое дело, возможен ли такой кейс, и если нет, то верное ли прописано условие?

2016-12-05 10:17 UTC, vkurennov requested changes

2016-12-05 10:17 UTC, vkurennov commented on app/controllers/omniauth_callbacks_controller.rb
> +    if @user && @user.persisted?
Да, и этот кейс надо покрывать на уровне контроллера.

2016-12-05 14:24 UTC, vkurennov approved these changes

2016-12-05 14:43 UTC, merged