5.acceptance tests
di8905/asky pull request #3
Opened 2016-10-20 05:56 UTC by di8905

Косяков наверное море, простите, трудно далось задание ))

2016-10-20 10:26 UTC, vkurennov requested changes
Исправь замечания

2016-10-20 10:26 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +     if @answer.user == current_user
Надо проверять по id, чтобы не тянуть юзера из базы, ведь сам объект нам не нужен, надо только понять, является ли текущий юзер автором, а для этого достаточно сравнить id.

2016-10-20 10:26 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +       redirect_to @question, notice: "Answer deleted"
Редирект одинаковый, только сообщение отличается, значит, надо вынести редирект из условия, а в условии оставить только установку флеш-сообщения

2016-10-20 10:26 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
Форма ответа должна быть на странице вопроса, поэтому и рендерить надо страницу вопроса

2016-10-20 10:26 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user
Те же замечания, что и в AnswersController. И еще одно: такая проверка будет часто встречаться, поэтому ее лучше вынести в модель User, чтобы вызывать так: `current_user.author_of?(@question)`

2016-10-20 10:26 UTC, vkurennov commented on app/models/answer.rb
> +  validates :user, presence: true
У тебя же 5-е рельсы, поэтому валидацию на ассоциации belongs_to ставить не надо, она автоматом будет выполнена

2016-10-20 10:26 UTC, vkurennov commented on app/models/question.rb
> +  validates :user, presence: true
Это лишнее

2016-10-20 10:26 UTC, vkurennov commented on app/models/user.rb
>    validates :email, format: { with: EMAIL, message: 'incorrect email' }
Модуль validatable у devise уже проводит валидации на формат email, его уникальность, длинну пароля и его совпадение с подтверждением. Так что, убери лишние проверки

2016-10-20 10:26 UTC, vkurennov commented on app/views/answers/new.html.slim
> +h1 New answer
Форма ответа должна быть на странице вопроса, так написано в задании

2016-10-20 10:26 UTC, vkurennov commented on app/views/questions/index.html.slim
> +    -if @questions
Надо проверять на `empty?`, т.к. если в  @questions будет пустой массив, это все равно как true посчитается

2016-10-20 10:26 UTC, vkurennov commented on app/views/questions/show.html.slim
> +=link_to 'Delete question', question_path(@question), method: :delete, class: "btn btn-danger"
Ссылка на удаление должна быть видна только автору

2016-10-20 10:26 UTC, vkurennov commented on db/migrate/20161017093513_add_password_to_user.rb
> +    add_column :users, :password, :string
Никогда не храни пароль в открытом виде, да и devise уже добавил нужные поля в таблицу, но он хранит пароли в зашифрованном виде

2016-10-20 10:26 UTC, vkurennov commented on spec/acceptance/answers/create_answer_spec.rb
> +    expect(current_path).to eq question_path(question)
Надо проверить, что на странице есть текст ответа

2016-10-20 10:26 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +    expect { delete_action }.to change(Answer, :count).by(-1)
В acceptance-тестах мы не проверяем изменения в базе, проверяем только то, что может увидеть пользователь. Это как живому тестеру писать задание. Ты же не напишешь "нажми удалить и зайди в базу посмотреть, что в таблице answers удалилась строка". Ты напишешь "нажми удалить и проверь, что на странице больше нет удаленного ответа". Вот так и надо писать acceptance-тесты.

2016-10-20 10:26 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +    expect { delete_action }.not_to change(Answer, :count)
проверяй изменения на странице, а не в базе

2016-10-20 10:26 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +    expect { delete_action }.not_to change(Answer, :count)
И здесь достаточно проверить, что не видна ссылка на удаление

2016-10-20 10:26 UTC, vkurennov commented on spec/acceptance/questions/delete_question_spec.rb
> +feature 'delete question', %q{
Те же замечания, что и к удалению вопроса

2016-10-20 10:26 UTC, vkurennov commented on spec/acceptance/questions/view_question_spec.rb
> +  given(:check_expectations) do
given,  как следует из названия, существует для задания начальных данных, а не для проверки. все проверки должны быть в тестах

2016-10-20 13:52 UTC, di8905 commented
1. По поводу замечаний что у меня 5-е рельсы - у меня четвертые. Просто решил что материалы для четвертых ведь. Плюс некоторые ручные фишки лучше знать по четвертым рельсам, а уже потом доизучать как оно в пятых. Не знаю, прав ли я, но пока так.
2. Мы проверяем что кнопка удаления для чужого автора не видна. Но на уровне контроллера наверное стоит покрыть тестом кейс "даже без кнопки кто то сделал вызов контроллеру удалить чужой вопрос"? Только не могу сконструировать тест на уровне контроллера, не соображу.

2016-10-21 09:08 UTC, vkurennov requested changes
Исправь замечания

2016-10-21 09:08 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @question.reload
А зачем повторно грузить вопрос из базы? Чтобы не отображать в списке несохраненный ответ? Тогда лучше при выводе ответов у каждого вызывать метод `persisted?`, который как раз определяет, сохранен в базе объект или нет.

2016-10-21 09:08 UTC, vkurennov commented on app/models/answer.rb
> +  validates :user, presence: true
Раз у тебя 4-е рельсы, то да, тогда проверять надо. Но лучше проверять user_id, т.к. в текущем варианте при валидации ответа из базы загружается еще и юзер и он тоже валидируется. Все это ведет к увеличению времени работы, что совершенно не обязательно

2016-10-21 09:08 UTC, vkurennov commented on app/models/user.rb
> +    id == entity.try(:user).try(:id)
Тут ты сломал всю идею сравнения по id :-). Смотри, фактически, у тебя вызов такой: `entity.user.id`, т.е. мы у объекта сначала **из базы в память загружаем ассоциацию user** и потом у нее берем id. Это долго и тратит память. А зачем нам из базы грузить юзера, когда у объекта есть поле user_id, и мы можем сравнить значение в нем, без загрузки ассоциации?

2016-10-21 09:08 UTC, vkurennov commented on db/migrate/20161017093513_add_password_to_user.rb
> +    add_column :users, :password, :string
Собственно, эту миграцию надо откатить и  удалить. Либо сделать новую миграцию, удаляющую это поле

2016-10-21 09:08 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +  scenario 'only author sees delete button' do
Еще нужен аналогичный сценарий для незалогиненного юзера, что он тоже не видит ссылок на удаление.

2016-10-21 09:08 UTC, vkurennov commented on spec/acceptance/questions/delete_question_spec.rb
> +  scenario 'only author can see delete button' do
И аналогичный сценарий для незалогиненного юзера

2016-10-21 09:08 UTC, vkurennov commented on spec/acceptance/questions/view_question_spec.rb
> +    (1..3).each { |i| FactoryGirl.create(:question, title: "Title number: #{i}") }
Можно использовать sequence в фабриках, чтобы делать заголовки уникальными и затем создать список через create_list

2016-10-21 09:08 UTC, vkurennov commented on spec/acceptance/questions/view_question_spec.rb
> +feature 'view question with answers', %q{
Каждая фича должна быть в отдельном файле. Либо ты можешь сделать фичу "просмотр вопроса" и там разные сценарии - на просмотр вопроса и списка ответов

2016-10-21 09:08 UTC, vkurennov commented on spec/acceptance/questions/view_question_spec.rb
> +    expect(page).to have_content('MyText must be at least 10 letters')
Надо проверить, что юзер видит **список** ответов. Т.е. должно быть несколько разных ответов на странице

2016-10-21 09:08 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
Здесь нужен тест на то, что созданный ответ связывается с залогиненным юзером

2016-10-21 09:08 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    end
В тестах на удаление должно быть 2 конекста: один для автора, другой для не-автора.

2016-10-21 09:08 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>        it 'saves new question in database' do
Нужен тест на то, что созданный вопрос связывается с залогиненным юзером

2016-10-21 09:08 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
В тестх на удаление должно быть 2 контекста: для автора и для не-автора

2016-10-21 09:08 UTC, vkurennov commented on spec/models/user_spec.rb
> +    expect(user.author_of?(question)).to eq true
В юнит-тетсах принято правило "один тест - один expect", раздели на 2 теста.

Вообще, в тестах моделей методы принято тестироват так: создаешь describe на метод с его названием и внутри уже пошли тесты, например, так:

```
describe "#author_of?" do
  it 'returns true for author'
  it 'returns false for non author'
end
```

2016-10-21 09:12 UTC, vkurennov commented
> По поводу замечаний что у меня 5-е рельсы - у меня четвертые. Просто решил что материалы для четвертых ведь. Плюс некоторые ручные фишки лучше знать по четвертым рельсам, а уже потом доизучать как оно в пятых. Не знаю, прав ли я, но пока так.

Большой разницы между 5-ми и 4-ми нет, поэтому почти все, что в скринкастах говорится, актуально и для 5-й версии, поэтому ее можно использовать без проблем. Ну и в середине курса уже будет задание по 5-м релсьам (ActionCable), так что лучше сейчас обновить.


> Мы проверяем что кнопка удаления для чужого автора не видна. Но на уровне контроллера наверное стоит покрыть тестом кейс "даже без кнопки кто то сделал вызов контроллеру удалить чужой вопрос"? Только не могу сконструировать тест на уровне контроллера, не соображу.

Конечно, на уровне контроллера такой тест должен быть обязательно. И написать его надо так, как до этого был у тебя написан acceptance-тест. То есть, делашь в контекста: для автора и для не-автора. В первом через let создаешь ответ, у которого в качестве юзера задан тот, которого мы логиним в контроллере (доступен как переменная @user в тестах). Далее делаешь запрос на удаление и проверяшь, что кол-во ответов в базе изменилось на 1. Для не-автора создаешь ответ от любого юзера и тоже делаешь запрос на удаление, но проверяешь, что кол-во не изменилось.
То же самое для вопросов

2016-10-21 14:50 UTC, vkurennov requested changes
Исправь замечания

2016-10-21 14:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(answer.user_id).to eq user.id
answer - это ответ, который ты в тестах через let создаешь, как и user. А тебе надо проверить у только что созданного в контроллере ответа и у залогиненного юзера. Ответ ты можешь достать через assigns, а юзер доступен через переменную @user (мы ее объявляем в методе sign_in_user)

2016-10-21 14:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        @request.env['devide.mapping'] = Devise.mappings[:user]
Это здесь зачем? Просто создай ответ от другого пользователя и все.

2016-10-21 14:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, question_id: question.id, id: answer }.not_to change(Answer, :count)
Он у тебя не меняет значение, потому что снчала ответ создается, при вызове answer и тут же удаляется, поэтому общее кол-во то же самое остается. Ты создай ответ ДО запроса на удаление и проверь, что кол-во не имзенилось

2016-10-21 14:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        answer
Чтобы не вызывать метод вручную, можешь объявить его через `let!`, тогда он будет вызываться перед каждым тестом.

2016-10-21 14:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect(question.user_id).to eq user.id
И опять же, это не тот вопрос и не тот юзер. Этих ты самолично в тестах создал и связал, само собой тест проходит, а надо проверить, что происходит в контроллере

2016-10-21 14:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, id: question }.not_to change(Question, :count)
И тут надо создавать вопрос ДО теста

2016-10-21 14:50 UTC, vkurennov commented on spec/models/user_spec.rb
> +  let(:prepare_data) do
Замени это на блок before, и не надо никаких prepare_data.

2016-10-21 14:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        sign_in FactoryGirl.create(:user)
И где объявлен этот метод? Откуда он взялся? Да и зачем логинить другого пользователя? Логинь того же самого, а вот вопрос создай от имени другого

2016-10-23 09:43 UTC, vkurennov approved these changes

2016-10-23 13:18 UTC, merged