9.ajax json
di8905/asky pull request #7
Opened 2016-11-18 16:19 UTC by di8905

2016-11-18 16:52 UTC, vkurennov requested changes
Исправь замечания

2016-11-18 16:52 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def vote
У тебя же консерн есть с таким методом.

2016-11-18 16:52 UTC, vkurennov commented on app/controllers/concerns/votes.rb
> +    @voteable.vote(current_user.id, params[:value])
1. А зачем id юзера передавать, когда можно сам объект? Тогда не нужно будет его заново из базы грузить

2016-11-18 16:52 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def vote
Зачем тебе тогда консерн, если ты его не используешь?

2016-11-18 16:52 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +    def vote(user_id, vote)
Это не в included должно быть, иначе эти методы включаются как методы класса

2016-11-18 16:52 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +      self.votes.each do |record|
Считать перебором, да еще и в руби - очень медленно и неоптимально по памяти. Гораздо лучше переложить это на базу, используя метод sum

2016-11-18 16:52 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +
Тут end надо добавить, закрыв блок included

2016-11-18 16:52 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +      vote_collection = self.votes.where(user_id: user_id)
зачем загружать голоса, если они сами по себе не нужны. Используй метод `exists?`, чтобы проверить, есть ли в базе нужные записи или нет.

2016-11-18 16:52 UTC, vkurennov commented on app/controllers/concerns/votes.rb
> +    @voteable.vote(current_user.id, params[:value])
2. Не надо передавать значение голоса из параметров, т.к. его легко подменить и сделать накрутку в +/- 100500 голосов.

2016-11-20 11:14 UTC, di8905 commented on app/controllers/concerns/votes.rb
> +    @voteable.vote(current_user.id, params[:value])
Виталь, поясни пожалуйста, не врубаюсь где использовать id а где объект. Идея моя была в том, что в метод мы передаем id юзера цифирькой и там же ею оперируем и записываем в таблицу votes и сверяем цифирку. Юзера как такового я нигде не грузил из базы, тупо цифирька передавалась проверялась и записывалась.
Как я тебя понял, ты предлагаешь передавать в метод сам объект. А зачем? Если кроме цифирки его айди нас ничего не интересует. Я переделал как тебя понял, но надеюсь ты мне распишешь где я чего не догоняю. =)

2016-11-20 17:56 UTC, vkurennov commented on app/controllers/concerns/votes.rb
> +    @voteable.vote(current_user.id, params[:value])
Да тут все просто, у тебя же уже есть объект current_user, он уже загружен из базы, поэтому предавать проще объект, передавая id ты ничего не выигрываешь. Правило можно сформулировать так: присваиваем по объектам (и передаем тоже), сравниваем по id. Но это не четкое правило, скорее просто руководство, всегда есть исключения.

2016-11-20 18:03 UTC, vkurennov requested changes

2016-11-20 18:03 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +      if self.user.id == user.id
А вот здесь как раз сравнивать лучше с self.user_id, чтобы не грузить ассоциацию у текущего объекта.

2016-11-20 18:03 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +        sum += record.vote
Ну и что изменилось? Все еще перебор, все еще объекты считаем средствами руби. Я же написал - используй метод sum из ActiveRecord

2016-11-20 18:03 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +      vote_collection = self.votes.where(user_id: user.id)
Раз уж у тебя объект, то можно писать `where(user: user)`. И вообще везде, где ты подставляешь user_id, можно заменить на user, чтобы работать с объектами.

2016-11-20 18:03 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +        self.errors.add(:base, 'Already voted this!') if vote_collection.first.vote == vote
Вообще, валидация на уникальность должна быть в модели Vote

2016-11-20 18:03 UTC, vkurennov commented on app/models/vote.rb
> +class Vote < ApplicationRecord
Добавь валидации на уникальность и на возможные значения: 1 и -1

2016-11-20 18:03 UTC, vkurennov commented on spec/models/concerns/voteable_spec.rb
> +  describe 'vote method tests' do
Нигде не тестируется какие ошибки валидации и в каких случаях добавляются, а ведь от этого зависит поведение контроллера.

2016-11-21 06:13 UTC, di8905 commented on app/models/concerns/voteable.rb
> +      vote_collection = self.votes.where(user_id: user.id)
self.votes.where(user: user) - сделал так, но это вызывает ошибку, у меня же нет поля user для vote, не задана ассоциация. Я в таблице храню просто user_id, но ассоциацию не делал для простоты. Или считаешь что она нужна?

2016-11-21 07:19 UTC, di8905 commented on spec/models/vote_spec.rb
> +  it { should validate_uniqueness_of(:user).scoped_to(:voteable) }
Вот этот тест не проходит, не могу  сделать правильно, обгуглился уже до посинения. Подскажи как верно сделать?

2016-11-21 11:05 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +      vote_collection = self.votes.where(user_id: user.id)
Так задай ассоциацию, в чем проблема? Поле-то все равно уже есть. Убрав ассоциацию, ты ничего не сэкономил

2016-11-21 11:24 UTC, vkurennov approved these changes

2016-11-21 11:24 UTC, vkurennov commented on app/models/concerns/voteable.rb
> +    if self.user == user
Здесь сравнение надо делать по id. Сравниваем по user_id, присваиваем по объектам. И вообще, у тебя есть метод User#author_of?, который и делает такое сравнение.

2016-11-21 13:18 UTC, vkurennov commented on spec/models/vote_spec.rb
> +  it { should validate_uniqueness_of(:user).scoped_to(:voteable) }
Так у тебя же скоуп по 2-м полям, вот и указывай оба как массив: `[votable_id, votable_type]`

2016-11-21 20:21 UTC, merged